# Generated by Django 3.2.3 on 2021-05-17 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210517_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 19, 40, 1, 759005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 19, 40, 1, 760553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 40, 1, 761527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 19, 40, 1, 763357, tzinfo=utc)),
        ),
    ]
