# Generated by Django 3.2.3 on 2021-05-17 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210517_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 46, 42, 682809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 46, 42, 686530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 46, 42, 688709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 46, 42, 692910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ended_on',
            field=models.DateTimeField(null=True),
        ),
    ]
