# Generated by Django 3.2.3 on 2021-05-17 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20210517_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 45, 46, 797846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 45, 46, 799537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 45, 46, 801210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 19, 45, 46, 804070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ended_on',
            field=models.DateTimeField(null=True),
        ),
    ]
