# Generated by Django 3.2.3 on 2021-05-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20210517_1946'),
        ('rareapi', '0004_auto_20210517_1945'),
    ]

    operations = [
    ]
