# Generated by Django 3.2.3 on 2021-05-19 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_merge_0003_auto_20210517_1946_0004_auto_20210517_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 14, 13, 45, 891675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='demotionqueue',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to='rareapi.rareuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rareapi.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 14, 13, 45, 893140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 14, 13, 45, 893870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 14, 13, 45, 895129, tzinfo=utc)),
        ),
    ]
