# Generated by Django 3.2.3 on 2021-05-20 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0006_auto_20210519_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 19, 7, 37, 800043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 19, 7, 37, 803016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 19, 7, 37, 804815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='image_url',
            field=models.ImageField(upload_to='reaction_images'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 19, 7, 37, 807820, tzinfo=utc)),
        ),
    ]
