# Generated by Django 3.2.3 on 2021-05-20 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0006_auto_20210519_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='demotionqueue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_to_change', to='rareapi.rareuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 20, 7, 10, 26104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 20, 7, 10, 28382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 20, 7, 10, 29582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='image_url',
            field=models.ImageField(upload_to='reaction_images'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 20, 7, 10, 31140, tzinfo=utc)),
        ),
    ]
